const $=s=>document.querySelector(s);let token=sessionStorage.getItem('pukkaAccessToken')||'',shipments=[],proposed='';
const api=async(path,options={})=>{const response=await fetch(path,{...options,headers:{'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{}),...(options.headers||{})}});const data=await response.json();if(!response.ok)throw new Error(data.error||'Request failed.');return data};
function setupFields(){const grid=document.querySelectorAll('#createShipment .form-grid')[2];grid.insertAdjacentHTML('beforeend','<label>Weight (kg) *<input name="weight" type="number" min="0.01" step="0.01" required></label><label>Shipment price (₦) *<input name="price" type="number" min="0" step="0.01" required></label>');const field=$('#statusShipment');field.outerHTML='<input name="trackingNumber" id="statusShipment" list="statusShipmentList" required placeholder="Enter or select PUK tracking ID">';$('#statusUpdate').insertAdjacentHTML('beforeend','<datalist id="statusShipmentList"></datalist>');$('.register-head').insertAdjacentHTML('beforeend','<button id="downloadCsv">Download CSV</button>')}
function newId(){return 'PUK-'+new Date().getFullYear()+'-'+String(shipments.length+1+Math.floor(Math.random()*900)).padStart(5,'0')}
function setProposed(){proposed=newId();$('#proposedId').textContent=proposed}
function money(v){return Number(v||0).toLocaleString('en-NG',{style:'currency',currency:'NGN',maximumFractionDigits:2})}
async function render(){shipments=await api('/api/shipments');$('#statusShipmentList').innerHTML=shipments.map(x=>'<option value="'+x.tracking_id+'">'+x.recipient_name+' · '+x.status+'</option>').join('');$('#shipmentTable').innerHTML=shipments.length?shipments.map(x=>'<div class="register-row"><div><strong>'+x.tracking_id+'</strong><small>'+x.recipient_name+'</small></div><div><strong>'+x.origin+' → '+x.destination+'</strong><small>'+(x.carrier_waybill?'Waybill: '+x.carrier_waybill:'Pukka Express delivery')+'</small></div><div class="register-carrier">'+(x.carrier==='standalone'?'PUKKA EXPRESS':x.carrier.toUpperCase())+'<small>'+x.status+'</small></div><div><strong>'+x.weight_kg+' kg</strong><small>'+money(x.price_ngn)+'</small><a href="tracking.html" class="row-link">Customer view</a></div></div>').join(''):'<p class="empty">No shipments created yet.</p>'}
async function dashboard(){const active=Boolean(token);$('#loginCard').hidden=active;$('#adminDashboard').hidden=!active;if(active)try{await render();setProposed()}catch(error){token='';sessionStorage.removeItem('pukkaAccessToken');$('#loginCard').hidden=false;$('#adminDashboard').hidden=true;$('#loginError').textContent=error.message;$('#loginError').hidden=false}}
function csvValue(v){return '"'+String(v??'').replace(/"/g,'""')+'"'}function downloadCsv(){const heads=['Pukka ID','Carrier','Carrier waybill','Status','Weight kg','Price NGN','Sender','Origin','Recipient','Destination','Recipient email','Recipient phone'];const body=shipments.map(x=>[x.tracking_id,x.carrier,x.carrier_waybill,x.status,x.weight_kg,x.price_ngn,x.sender_name,x.origin,x.recipient_name,x.destination,x.recipient_email,x.recipient_phone].map(csvValue).join(',')).join('\n');const url=URL.createObjectURL(new Blob([heads.map(csvValue).join(',')+'\n'+body],{type:'text/csv'})),a=document.createElement('a');a.href=url;a.download='pukka-express-shipments.csv';a.click();URL.revokeObjectURL(url)}
$('#loginForm').addEventListener('submit',async e=>{e.preventDefault();try{const f=new FormData(e.currentTarget),session=await api('/api/auth',{method:'POST',body:JSON.stringify({email:f.get('email'),password:f.get('password')})});token=session.access_token;sessionStorage.setItem('pukkaAccessToken',token);await dashboard()}catch(error){$('#loginError').textContent=error.message;$('#loginError').hidden=false}});
$('#logout').addEventListener('click',()=>{token='';sessionStorage.removeItem('pukkaAccessToken');dashboard()});$('#regenerate').addEventListener('click',setProposed);
$('#createShipment').addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.currentTarget),carrier=f.get('carrier'),payload={tracking_id:proposed,carrier,carrier_waybill:(f.get('waybill')||'').trim()||null,sender_name:f.get('senderName'),sender_email:f.get('senderEmail'),sender_phone:f.get('senderPhone'),sender_street:f.get('senderStreet'),recipient_name:f.get('recipient'),recipient_email:f.get('recipientEmail'),recipient_phone:f.get('recipientPhone'),recipient_street:f.get('recipientStreet'),origin:f.get('senderTown')+', '+f.get('senderCountry'),destination:f.get('recipientTown')+', '+f.get('recipientCountry'),weight_kg:Number(f.get('weight')),price_ngn:Number(f.get('price'))};try{const item=await api('/api/shipments',{method:'POST',body:JSON.stringify(payload)});fetch('/api/notify-shipment',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:item.tracking_id,recipient:item.recipient_name,recipientEmail:item.recipient_email,origin:item.origin,destination:item.destination,carrier:item.carrier,waybill:item.carrier_waybill,weight:item.weight_kg,price:item.price_ngn})});$('#createdMessage').innerHTML='Shipment created. Customer tracking ID: <strong>'+item.tracking_id+'</strong> <button type="button" id="copyTracking">⧉ Copy</button>';$('#copyTracking').addEventListener('click',async()=>{await navigator.clipboard.writeText(item.tracking_id);$('#copyTracking').textContent='Copied'});$('#createdMessage').hidden=false;e.currentTarget.reset();await render();setProposed()}catch(error){$('#createdMessage').textContent=error.message;$('#createdMessage').hidden=false}});
$('#statusUpdate').addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.currentTarget),trackingNumber=String(f.get('trackingNumber')||'').trim().toUpperCase(),shipment=shipments.find(x=>x.tracking_id.toUpperCase()===trackingNumber);if(!shipment){$('#statusMessage').textContent='That Pukka tracking ID is not in the shipment register.';$('#statusMessage').hidden=false;return}try{await api('/api/shipments',{method:'PATCH',body:JSON.stringify({shipment_id:shipment.id,status:f.get('status'),location:f.get('location'),note:f.get('note')})});$('#statusMessage').textContent='Update published for '+shipment.tracking_id+'.';$('#statusMessage').hidden=false;e.currentTarget.reset();await render()}catch(error){$('#statusMessage').textContent=error.message;$('#statusMessage').hidden=false}});
$('#clearShipments').addEventListener('click',()=>alert('Database records are intentionally not cleared from the browser. Remove records in Supabase only when required.'));setupFields();$('#downloadCsv').addEventListener('click',downloadCsv);dashboard();
