const $=s=>document.querySelector(s);
const storageKey='pukkaExpressShipments';
const legacyKey='parcelpathShipments';
const records=()=>{const current=localStorage.getItem(storageKey);return JSON.parse(current||localStorage.getItem(legacyKey)||'[]')};
const save=data=>localStorage.setItem(storageKey,JSON.stringify(data));
let proposed='';
function setupFields(){const grids=document.querySelectorAll('#createShipment .form-grid');const carrierGrid=grids[2];carrierGrid.insertAdjacentHTML('beforeend','<label>Weight (kg) *<input name="weight" type="number" min="0.01" step="0.01" required placeholder="e.g. 2.5"></label><label>Shipment price (₦) *<input name="price" type="number" min="0" step="0.01" required placeholder="e.g. 15000"></label>');$('.register-head').insertAdjacentHTML('beforeend','<button id="downloadCsv">Download CSV</button>')}
function newId(){return 'PUK-'+new Date().getFullYear()+'-'+String(records().length+1+Math.floor(Math.random()*900)).padStart(5,'0')}
function setProposed(){proposed=newId();$('#proposedId').textContent=proposed}
function dashboard(){const yes=sessionStorage.getItem('pukkaExpressAdmin')==='yes'||sessionStorage.getItem('parcelpathAdmin')==='yes';$('#loginCard').hidden=yes;$('#adminDashboard').hidden=!yes;if(yes){sessionStorage.setItem('pukkaExpressAdmin','yes');setProposed();render()}}
function eventRows(item){const updates=Array.isArray(item.events)?item.events:[];return updates.length?updates[0].title+' · '+updates[0].time:'No manual Pukka updates'}
function money(value){return Number(value||0).toLocaleString('en-NG',{style:'currency',currency:'NGN',maximumFractionDigits:2})}
function render(){const data=records();const select=$('#statusShipment');select.innerHTML=data.length?'<option value="">Select a Pukka shipment</option>'+data.map(x=>'<option value="'+x.id+'">'+x.id+' — '+x.recipient+'</option>').join(''):'<option value="">Create a shipment first</option>';$('#shipmentTable').innerHTML=data.length?data.map(x=>'<div class="register-row"><div><strong>'+x.id+'</strong><small>'+x.recipient+'</small></div><div><strong>'+x.origin+' → '+x.destination+'</strong><small>'+(x.waybill?'Waybill: '+x.waybill:'Pukka Express delivery')+'</small></div><div class="register-carrier">'+(x.carrier==='standalone'?'PUKKA EXPRESS':x.carrier.toUpperCase())+'<small>'+eventRows(x)+'</small></div><div><strong>'+x.weight+' kg</strong><small>'+money(x.price)+'</small><a href="tracking.html" class="row-link">Customer view</a></div></div>').join(''):'<p class="empty">No shipments created yet.</p>'}
async function notifyCustomer(item){try{const response=await fetch('/api/notify-shipment',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(item)});const data=await response.json();return response.ok&&data.sent}catch{return false}}
function csvValue(value){return '"'+String(value??'').replace(/"/g,'""')+'"'}
function downloadCsv(){const rows=records();const headers=['Pukka tracking ID','Carrier','Carrier waybill','Status','Weight (kg)','Price (NGN)','Sender','Origin','Recipient','Destination','Recipient email','Recipient phone','Created/updated'];const body=rows.map(x=>[x.id,x.carrier==='standalone'?'Pukka Express':String(x.carrier||'').toUpperCase(),x.waybill,x.status,x.weight,x.price,x.senderName,x.origin,x.recipient,x.destination,x.recipientEmail,x.recipientPhone,x.updatedAt||x.events?.[0]?.time||''].map(csvValue).join(',')).join('\n');const blob=new Blob([headers.map(csvValue).join(',')+'\n'+body],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download='pukka-express-shipments.csv';link.click();URL.revokeObjectURL(url)}
$('#loginForm').addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.currentTarget);const email=f.get('email'),password=f.get('password');if((email==='admin@pukkaexpress.ng'&&password==='PukkaExpress2026!')||(email==='admin@parcelpath.local'&&password==='ParcelPath2026!')){sessionStorage.setItem('pukkaExpressAdmin','yes');dashboard()}else $('#loginError').hidden=false});
$('#logout').addEventListener('click',()=>{sessionStorage.removeItem('pukkaExpressAdmin');sessionStorage.removeItem('parcelpathAdmin');dashboard()});
$('#regenerate').addEventListener('click',setProposed);
$('#createShipment').addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.currentTarget),carrier=f.get('carrier'),waybill=(f.get('waybill')||'').trim(),item={id:proposed,recipient:f.get('recipient'),recipientEmail:f.get('recipientEmail'),recipientPhone:f.get('recipientPhone'),recipientStreet:f.get('recipientStreet'),recipientZip:f.get('recipientZip'),senderName:f.get('senderName'),senderEmail:f.get('senderEmail'),senderPhone:f.get('senderPhone'),senderStreet:f.get('senderStreet'),senderZip:f.get('senderZip'),origin:f.get('senderTown')+', '+f.get('senderCountry'),destination:f.get('recipientTown')+', '+f.get('recipientCountry'),carrier,waybill,weight:Number(f.get('weight')),price:Number(f.get('price')),status:'Shipment received',events:[{title:'Shipment received',location:f.get('senderTown')+', '+f.get('senderCountry'),time:'Just now'}]};save([item,...records()]);const sent=await notifyCustomer(item);$('#createdMessage').textContent='Shipment created. Customer tracking ID: '+item.id+(sent?' — confirmation email sent.':' — email notification is not configured yet.');$('#createdMessage').hidden=false;e.currentTarget.reset();setProposed();render()});
$('#statusUpdate').addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.currentTarget),id=f.get('shipmentId'),data=records(),item=data.find(x=>x.id===id);if(!item)return;const location=f.get('location').trim(),note=f.get('note').trim(),status=f.get('status'),time=new Date().toLocaleString('en-NG',{dateStyle:'medium',timeStyle:'short'});item.status=status;item.events=Array.isArray(item.events)?item.events:[];item.events.unshift({title:status+(note?' — '+note:''),location,time});item.updatedAt=time;save(data);$('#statusMessage').textContent='Update published for '+id+'.';$('#statusMessage').hidden=false;e.currentTarget.reset();render()});
$('#clearShipments').addEventListener('click',()=>{localStorage.removeItem(storageKey);localStorage.removeItem(legacyKey);render()});
setupFields();$('#downloadCsv').addEventListener('click',downloadCsv);dashboard();
