const $=s=>document.querySelector(s);let chosen='auto',lastLookup=null;const records=()=>JSON.parse(localStorage.getItem('parcelpathShipments')||'[]');
function detect(value){if(chosen!=='auto')return chosen;if(/^\d{12}$|^\d{15}$/.test(value))return'fedex';if(/^\d{10}$/.test(value))return'aramex';return'dhl'}
function localTracking(number){const s=records().find(x=>x.id.toLowerCase()===number.toLowerCase()||x.waybill.toLowerCase()===number.toLowerCase());return s&&{carrier:s.carrier==='standalone'?'Pukka Express':s.carrier.toUpperCase(),route:s.origin+' → '+s.destination,status:'Shipment created',eta:'Updates will appear here',title:'Shipment registered',events:[['Shipment created',s.origin,'Just now']]}}
function carrierMark(carrier){const mark=$('#carrierLogo'),name=carrier.toLowerCase();mark.style.cssText='';if(name.includes('fedex')){mark.style.cssText='background:#fff;border:1px solid #e6e8ef;font:800 15px Arial;letter-spacing:-1px';mark.innerHTML='<span style="color:#4d148c">Fed</span><span style="color:#ff6200">Ex</span>'}else if(name.includes('dhl')){mark.style.cssText='background:#ffcc00;color:#d40511;font:800 italic 15px Arial';mark.textContent='DHL'}else if(name.includes('aramex')){mark.style.cssText='background:#fff;color:#d71920;border:1px solid #e6e8ef;font:800 12px Arial';mark.textContent='aramex'}else{mark.style.cssText='background:#eaf0ff;color:#2559e6;font:800 10px Manrope';mark.textContent='Pukka'}}
function show(data,number,source='live'){const parts=(data.route||'Origin → Destination').split(' → '),origin=parts[0]||'Origin',destination=parts[1]||'Destination',summary=$('.shipment-summary'),details=$('.detail-grid');summary.hidden=false;details.hidden=false;summary.style.display='grid';details.style.display='grid';carrierMark(data.carrier);$('#carrierName').textContent=data.carrier.toUpperCase();$('#resultNumber').textContent=number;$('#route').innerHTML=origin+' <span>→</span> '+destination;$('#status').textContent=data.status;$('#eta').innerHTML='Estimated delivery <b>'+data.eta+'</b>';$('#deliveryTitle').textContent=data.title;$('#originName').textContent=origin;$('#originCaption').textContent=data.events[0]?.[1]||'Shipment origin';$('#destinationName').textContent=destination;$('#destinationCaption').textContent='Expected destination';$('#carrierLink').href=data.link||'mailto:pukkaexpress.ng@gmail.com';$('#timeline').innerHTML=data.events.length?data.events.map((e,i)=>'<div class="event '+(i===0?'current':'')+'"><i></i><strong>'+e[0]+'</strong><p>'+e[1]+'</p><small>'+e[2]+'</small></div>').join(''):'<p style="font-size:11px;color:#78869a">The carrier did not return any scan events.</p>';$('#apiError').hidden=true;$('#lastUpdated').textContent=source==='live'?'Live carrier data · updated just now':'Pukka Express record · updated just now';$('#resultShell').hidden=false;$('#resultShell').scrollIntoView({behavior:'smooth'})}
async function lookupLive(number,carrier){const response=await fetch('/api/track?carrier='+carrier+'&trackingNumber='+encodeURIComponent(number));const data=await response.json();if(!response.ok)throw new Error(data.error||'The carrier did not return a tracking result.');return data}
function showLiveError(message){const summary=$('.shipment-summary'),details=$('.detail-grid');summary.hidden=true;details.hidden=true;summary.style.display='none';details.style.display='none';$('#lastUpdated').textContent='No live result available';$('#apiError').textContent='Live tracking unavailable: '+message+' Configure carrier credentials and deploy the /api/track endpoint, then try again.';$('#apiError').hidden=false;$('#resultShell').hidden=false;$('#resultShell').scrollIntoView({behavior:'smooth'})}
document.querySelectorAll('.carrier').forEach(b=>b.addEventListener('click',()=>{chosen=b.dataset.carrier;document.querySelectorAll('.carrier').forEach(x=>x.classList.toggle('selected',x===b))}));
$('#trackerForm').addEventListener('submit',async e=>{e.preventDefault();const number=$('#trackingNumber').value.trim(),local=localTracking(number),button=e.submitter;if(local)return show(local,number,'local');const carrier=detect(number);button.textContent='Checking live status...';button.disabled=true;try{const data=await lookupLive(number,carrier);lastLookup={number,carrier};show(data,number)}catch(error){showLiveError(error.message)}finally{button.innerHTML='Track shipment <span>→</span>';button.disabled=false}});
$('#back').addEventListener('click',()=>{$('#resultShell').hidden=true;$('#trackingNumber').focus();scrollTo({top:0,behavior:'smooth'})});$('#refresh').addEventListener('click',async()=>{if(!lastLookup)return;const button=$('#refresh');button.textContent='Refreshing...';button.disabled=true;try{show(await lookupLive(lastLookup.number,lastLookup.carrier),lastLookup.number)}catch(error){showLiveError(error.message)}finally{button.innerHTML='↻ Refresh';button.disabled=false}});
