const $=s=>document.querySelector(s);let chosen='auto',lastLookup=null;
const readStore=key=>{try{const data=JSON.parse(localStorage.getItem(key)||'[]');return Array.isArray(data)?data:[]}catch{return []}};
const records=()=>{const merged=new Map();[...readStore('parcelpathShipments'),...readStore('pukkaExpressShipments')].forEach(item=>merged.set(String(item.id||item.waybill||Math.random()),item));return [...merged.values()]};
function detect(value){if(chosen!=='auto')return chosen;if(/^\d{12}$|^\d{15}$/.test(value))return'fedex';if(/^\d{10}$/.test(value))return'aramex';return'dhl'}
function findRecord(number){const key=number.toLowerCase();return records().find(x=>String(x.id||'').toLowerCase()===key||String(x.waybill||'').toLowerCase()===key)}
function localTracking(s){if(!s)return null;const updates=Array.isArray(s.events)?s.events:[];const timestamp=new Date().toLocaleString('en-NG',{dateStyle:'medium',timeStyle:'short'});const events=updates.length?updates.map(e=>[e.title||s.status||'Shipment update',e.location||s.origin,e.time||timestamp]):[[s.status||'Shipment created',s.origin,timestamp]];return{carrier:s.carrier==='standalone'?'Pukka Express':String(s.carrier||'Pukka Express').toUpperCase(),route:(s.origin||'Origin')+' → '+(s.destination||'Destination'),status:s.status||'Shipment created',eta:s.status==='Delivered'?'Delivered':'Updates will appear here',title:s.status||'Shipment registered',events}}
function carrierMark(carrier){const mark=$('#carrierLogo'),name=carrier.toLowerCase();mark.style.cssText='';if(name.includes('fedex')){mark.style.cssText='background:#fff;border:1px solid #e6e8ef;font:800 15px Arial;letter-spacing:-1px';mark.innerHTML='<span style="color:#4d148c">Fed</span><span style="color:#ff6200">Ex</span>'}else if(name.includes('dhl')){mark.style.cssText='background:#ffcc00;color:#d40511;font:800 italic 15px Arial';mark.textContent='DHL'}else if(name.includes('aramex')){mark.style.cssText='background:#fff;color:#d71920;border:1px solid #e6e8ef;font:800 12px Arial';mark.textContent='aramex'}else{mark.style.cssText='background:#eaf0ff;color:#2559e6;font:800 10px Manrope';mark.textContent='Pukka'}}
function show(data,number,source='live'){const parts=(data.route||'Origin → Destination').split(' → '),origin=parts[0]||'Origin',destination=parts[1]||'Destination',summary=$('.shipment-summary'),details=$('.detail-grid');summary.hidden=false;details.hidden=false;summary.style.display='grid';details.style.display='grid';carrierMark(data.carrier);$('#carrierName').textContent=data.carrier.toUpperCase();$('#resultNumber').textContent=number;$('#route').innerHTML=origin+' <span>→</span> '+destination;$('#status').textContent=data.status;$('#eta').innerHTML='Estimated delivery <b>'+data.eta+'</b>';$('#deliveryTitle').textContent=data.title;$('#originName').textContent=origin;$('#originCaption').textContent=data.events[0]?.[1]||'Shipment origin';$('#destinationName').textContent=destination;$('#destinationCaption').textContent='Expected destination';$('#carrierLink').href=data.link||'mailto:pukkaexpress.ng@gmail.com';$('#timeline').innerHTML=data.events.length?data.events.map((e,i)=>'<div class="event '+(i===0?'current':'')+'"><i></i><strong>'+e[0]+'</strong><p>'+e[1]+'</p><small>'+e[2]+'</small></div>').join(''):'<p style="font-size:11px;color:#78869a">No shipment updates are available yet.</p>';$('#apiError').hidden=true;$('#lastUpdated').textContent=source==='live'?'Live carrier data · updated just now':'Pukka Express update · updated just now';$('#resultShell').hidden=false;$('#resultShell').scrollIntoView({behavior:'smooth'})}
async function lookupLive(number,carrier){const response=await fetch('/api/track?carrier='+carrier+'&trackingNumber='+encodeURIComponent(number));const data=await response.json();if(!response.ok)throw new Error(data.error||'The carrier did not return a tracking result.');return data}
async function lookupPukka(number){const response=await fetch('/api/shipments?trackingNumber='+encodeURIComponent(number));if(response.status===404||response.status===503)return null;const data=await response.json();if(!response.ok)throw new Error(data.error||'Could not load Pukka shipment.');return data}
function showLiveError(message){const summary=$('.shipment-summary'),details=$('.detail-grid');summary.hidden=true;details.hidden=true;summary.style.display='none';details.style.display='none';$('#lastUpdated').textContent='No live result available';$('#apiError').textContent='Live tracking unavailable: '+message+' Configure carrier credentials and deploy the /api/track endpoint, then try again.';$('#apiError').hidden=false;$('#resultShell').hidden=false;$('#resultShell').scrollIntoView({behavior:'smooth'})}
document.querySelectorAll('.carrier').forEach(b=>b.addEventListener('click',()=>{chosen=b.dataset.carrier;document.querySelectorAll('.carrier').forEach(x=>x.classList.toggle('selected',x===b))}));
$('#trackerForm').addEventListener('submit',async e=>{e.preventDefault();const number=$('#trackingNumber').value.trim(),record=findRecord(number),button=e.submitter;if(!number)return;button.textContent='Checking live status...';button.disabled=true;try{const pukka=await lookupPukka(number);if(pukka){show(pukka,number,'pukka')}else if(record){const local=localTracking(record),hasCarrierWaybill=record.carrier&&record.carrier!=='standalone'&&record.waybill;if(hasCarrierWaybill){try{const live=await lookupLive(record.waybill,record.carrier);live.route=live.route||local.route;lastLookup={number:record.waybill,carrier:record.carrier,displayNumber:number};show(live,number)}catch(error){show(local,number,'local')}}else show(local,number,'local')}else{const carrier=detect(number),data=await lookupLive(number,carrier);lastLookup={number,carrier,displayNumber:number};show(data,number)}}catch(error){showLiveError(error.message)}finally{button.innerHTML='Track shipment <span>→</span>';button.disabled=false}});
$('#back').addEventListener('click',()=>{$('#resultShell').hidden=true;$('#trackingNumber').focus();scrollTo({top:0,behavior:'smooth'})});
$('#refresh').addEventListener('click',async()=>{if(!lastLookup)return;const button=$('#refresh');button.textContent='Refreshing...';button.disabled=true;try{show(await lookupLive(lastLookup.number,lastLookup.carrier),lastLookup.displayNumber||lastLookup.number)}catch(error){showLiveError(error.message)}finally{button.innerHTML='↻ Refresh';button.disabled=false}});
